services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: candi-dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
